---
title: "Assignment - Module 4"
author: "Krishna Kumar Tavva"
date: "2023-09-24"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

## Install lpSolve package to facilitate solving our problem

```{r}
#install.packages("lpSolve") 
library(lpSolve)
```

```{r}
# Let X1, X2, X3 be the number of large-sized units produced at Plants 1, 2, and 3, respectively, per day.
# Let Y1, Y2, Y3 be the number of medium-sized units produced at Plants 1, 2, and 3, respectively, per day.
# Let Z1, Z2, Z3 be the number of small-sized units produced at Plants 1, 2, and 3, respectively, per day.

# Objective Function
# Maximize Z = 420(X1+X2+X3) + 360(Y1+Y2+Y3) + 300(Z1+Z2+Z3)

f.obj<-c(420,360,300,420,360,300,420,360,300)

# Subject to
#   X1 + Y1 + Z1 ≤ 750
#   X2 + Y2 + Z2 ≤ 900
#   X3 + Y3 + Z3 ≤ 450
# 
#   20X1 + 15Y1 + 12Z1 ≤ 13000
#   20X2 + 15Y2 + 12Z2 ≤ 12000
#   20X3 + 15Y3 + 12Z3 ≤ 5000
# 
#   X1 + X2 + X3 ≤ 900
#   Y1 + Y2 + Y3 ≤ 1200
#   Z1 + Z2 + Z3 ≤ 750
#   
# Non Negativity
#     X1, X2, X3, Y1, Y2, Y3, Z1, Z2, Z3 ≥ 0

# Write down the above constraints using all 9 variables in each equation as follow:
# X1 + Y1 + Z1 + 0X2 + 0Y2 + 0Z2 + 0X3 + 0Y3 + 0Z3 ≤ 750
# 0X1 + 0Y1 + 0Z1 + X2 + Y2 + Z2 + 0X3 + 0Y3 + 0Z3 ≤ 900
# 0X1 + 0Y1 + 0Z1 + 0X2 + 0Y2 + 0Z2 + X3 + Y3 + Z3 ≤ 450
# 20X1 + 15Y1 + 12Z1 + 0X2 + 0Y2 + 0Z2 + 0X3 + 0Y3 + 0Z3 ≤ 13000
# 0X1 + 0Y1 + 0Z1 + 20X2 + 15Y2 + 12Z2 + 0X3 + 0Y3 + 0Z3 ≤ 12000
# 0X1 + 0Y1 + 0Z1 + 0X2 + 0Y2 + 0Z2 + 20X3 + 15Y3 + 12Z3 ≤ 5000
# X1 + 0Y1 + 0Z1 + X2 + 0Y2 + 0Z2 + X3 + 0Y3 + 0Z3 ≤ 900
# 0X1 + Y1 + 0Z1 + 0X2 + Y2 + 0Z2 + 0X3 + Y3 + 0Z3 ≤ 1200
# 0X1 + 0Y1 + Z1 + 0X2 + 0Y2 + Z2 + 0X3 + 0Y3 + Z3 ≤ 750

# The coefficients of the constraints can be written in the matrix form as
#   1 1 1 0 0 0 0 0 0
#   0 0 0 1 1 1 0 0 0
#   0 0 0 0 0 0 1 1 1
#   20 15 12 0 0 0 0 0 0
#   0 0 0 20 15 12 0 0 0
#   0 0 0 0 0 0 20 15 12
#   1 0 0 1 0 0 1 0 0
#   0 1 0 0 1 0 0 1 0
#   0 0 1 0 0 1 0 0 1
# 
# Formulating the Constraints in the Matrix form : 

f.con<- matrix(c(1,1,1,0,0,0,0,0,0,
                 0,0,0,1,1,1,0,0,0,
                 0,0,0,0,0,0,1,1,1,
                 20,15,12,0,0,0,0,0,0,
                 0,0,0,20,15,12,0,0,0,
                 0,0,0,0,0,0,20,15,12,
                 1,0,0,1,0,0,1,0,0,
                 0,1,0,0,1,0,0,1,0,
                 0,0,1,0,0,1,0,0,1), nrow=9, byrow=TRUE)

# Setting the direction of inequalities constraints
f.dir <- c("<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=",
           "<=")

# Setting the right hand side coefficients
f.rhs = c(750,900,450,13000,12000,5000,900,1200,750)

# Finding the value of Objective fUNCTION
lp("max",f.obj,f.con,f.dir,f.rhs)

# Getting the values of Variables
lp("max",f.obj,f.con,f.dir,f.rhs)$solution
```

